helpCfg:
  title: 丫丫帮助
  subTitle: 烟花易逝，人情长存。
helpList:
  - group: 功能列表
    list:
      - title: "#赞我"
        desc: 给我点赞
      - title: "#米游社版块签到"
        desc: 米游社社区版块签到,获取经验
      - title: "#过验证"
        desc: 米游社过图形验证码