helpCfg:
  title: 丫丫帮助
  subTitle: 天作孽，犹可违，自作孽，不可活。
helpList:
  - group: 功能列表
    list:
      - title: ^#(点赞|赞我|点zan)$
        desc: 给我点赞
  - group: 功能列表
    list:
      - title: ^#米游社版块签到
        desc: 米游社社区版块签到,获取经验
